# GENERATED by scripts/generate_schema.sh — do not edit.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class BinningMode(TypedDict):
    Name: str
    X: int
    Y: int


class CameraInfo(TypedDict):
    TargetTemp: NotRequired[float]
    AtTargetTemp: NotRequired[bool]
    CanSetTemperature: NotRequired[bool]
    HasShutter: NotRequired[bool]
    Temperature: NotRequired[float]
    Gain: NotRequired[int]
    DefaultGain: NotRequired[int]
    ElectronsPerADU: NotRequired[float]
    BinX: NotRequired[int]
    BitDepth: NotRequired[int]
    BinY: NotRequired[int]
    CanSetOffset: NotRequired[bool]
    CanGetGain: NotRequired[bool]
    OffsetMin: NotRequired[int]
    OffsetMax: NotRequired[int]
    Offset: NotRequired[int]
    DefaultOffset: NotRequired[int]
    USBLimit: NotRequired[int]
    IsSubSampleEnabled: NotRequired[bool]
    CameraState: NotRequired[
        Literal[
            'NoState',
            'Idle',
            'Waiting',
            'Exposing',
            'Reading',
            'Download',
            'Error',
            'LoadingFile',
        ]
    ]
    XSize: NotRequired[int]
    YSize: NotRequired[int]
    PixelSize: NotRequired[float]
    Battery: NotRequired[int]
    GainMin: NotRequired[int]
    GainMax: NotRequired[int]
    CanSetGain: NotRequired[bool]
    Gains: NotRequired[list[Any]]
    CoolerOn: NotRequired[bool]
    CoolerPower: NotRequired[float]
    HasDewHeater: NotRequired[bool]
    DewHeaterOn: NotRequired[bool]
    CanSubSample: NotRequired[bool]
    SubSampleX: NotRequired[int]
    SubSampleY: NotRequired[int]
    SubSampleWidth: NotRequired[int]
    SubSampleHeight: NotRequired[int]
    TemperatureSetPoint: NotRequired[float]
    ReadoutModes: NotRequired[list[str]]
    ReadoutMode: NotRequired[int]
    ReadoutModeForSnapImages: NotRequired[int]
    ReadoutModeForNormalImages: NotRequired[int]
    IsExposing: NotRequired[bool]
    ExposureEndTime: NotRequired[str]
    LastDownloadTime: NotRequired[float]
    SensorType: NotRequired[
        Literal[
            'Monochrome',
            'Color',
            'RGGB',
            'CMYG',
            'CMYG2',
            'LRGB',
            'BGGR',
            'GBRG',
            'GRBG',
            'GRGB',
            'GBGR',
            'RGBG',
            'BGRG',
        ]
    ]
    BayerOffsetX: NotRequired[int]
    BayerOffsetY: NotRequired[int]
    BinningModes: NotRequired[list[BinningMode]]
    ExposureMax: NotRequired[float]
    ExposureMin: NotRequired[float]
    LiveViewEnabled: NotRequired[bool]
    CanShowLiveView: NotRequired[bool]
    SupportedActions: NotRequired[list[str]]
    CanSetUSBLimit: NotRequired[bool]
    USBLimitMin: NotRequired[int]
    USBLimitMax: NotRequired[int]
    Connected: NotRequired[bool]
    Name: NotRequired[str]
    DisplayName: NotRequired[str]
    DeviceId: NotRequired[str]


class DomeInfo(TypedDict):
    ShutterStatus: NotRequired[
        Literal[
            'ShutterNone',
            'ShutterOpen',
            'ShutterClosed',
            'ShutterOpening',
            'ShutterClosing',
            'ShutterError',
        ]
    ]
    DriverCanFollow: NotRequired[bool]
    CanSetShutter: NotRequired[bool]
    CanSetPark: NotRequired[bool]
    CanSetAzimuth: NotRequired[bool]
    CanSyncAzimuth: NotRequired[bool]
    CanPark: NotRequired[bool]
    CanFindHome: NotRequired[bool]
    AtPark: NotRequired[bool]
    AtHome: NotRequired[bool]
    DriverFollowing: NotRequired[bool]
    Slewing: NotRequired[bool]
    Azimuth: NotRequired[int]
    SupportedActions: NotRequired[list[Any]]
    Connected: NotRequired[bool]
    Name: NotRequired[str]
    DisplayName: NotRequired[str]
    Description: NotRequired[str]
    DriverInfo: NotRequired[str]
    DriverVersion: NotRequired[str]
    DeviceId: NotRequired[str]
    IsFollowing: NotRequired[bool]
    IsSynchronized: NotRequired[bool]


class SelectedFilter(TypedDict):
    Name: NotRequired[str]
    Id: NotRequired[int]


class AvailableFilter(TypedDict):
    Name: str
    Id: int


class FWInfo(TypedDict):
    Connected: bool
    Name: str
    DisplayName: str
    Description: str
    DriverInfo: str
    DriverVersion: str
    DeviceId: str
    IsMoving: NotRequired[bool]
    SupportedActions: NotRequired[list[str]]
    SelectedFilter: NotRequired[SelectedFilter]
    AvailableFilters: NotRequired[list[AvailableFilter]]


class Binning(TypedDict):
    Name: str
    X: int
    Y: int


class FlatWizardFilterSettings(TypedDict):
    FlatWizardMode: int
    HistogramMeanTarget: float
    HistogramTolerance: float
    MaxFlatExposureTime: int
    MinFlatExposureTime: float
    MaxAbsoluteFlatDeviceBrightness: int
    MinAbsoluteFlatDeviceBrightness: int
    Gain: int
    Offset: int
    Binning: Binning


class AutoFocusBinning(TypedDict):
    Name: str
    X: int
    Y: int


class FilterInfo(TypedDict):
    Name: str
    FocusOffset: int
    Position: int
    AutoFocusExposureTime: int
    AutoFocusFilter: bool
    FlatWizardFilterSettings: FlatWizardFilterSettings
    AutoFocusBinning: AutoFocusBinning
    AutoFocusGain: int
    AutoFocusOffset: int


class FlatDeviceInfo(TypedDict):
    CoverState: Literal[
        'Unknown', 'NeitherOpenNorClosed', 'Closed', 'Open', 'Error', 'NotPresent'
    ]
    LocalizedCoverState: str
    LocalizedLightOnState: str
    LightOn: bool
    Brightness: int
    SupportsOpenClose: bool
    MinBrightness: int
    MaxBrightness: int
    SupportsOnOff: bool
    SupportedActions: list[Any]
    Connected: bool
    Name: str
    DisplayName: str
    Description: str
    DriverInfo: str
    DriverVersion: str
    DeviceId: str


class FocuserInfo(TypedDict):
    Position: int
    StepSize: int
    Temperature: float
    IsMoving: bool
    IsSettling: bool
    TempComp: bool
    TempCompAvailable: bool
    SupportedActions: list[Any]
    Connected: bool
    Name: str
    DisplayName: str
    Description: str
    DriverInfo: str
    DriverVersion: str
    DeviceId: str


class InitialFocusPoint(TypedDict):
    Position: int
    Value: float
    Error: int


class CalculatedFocusPoint(TypedDict):
    Position: float
    Value: float
    Error: int


class PreviousFocusPoint(TypedDict):
    Position: float
    Value: float
    Error: int


class MeasurePoint(TypedDict):
    Position: int
    Value: float
    Error: float


class TrendLineIntersection(TypedDict):
    Position: int
    Value: float
    Error: int


class HyperbolicMinimum(TypedDict):
    Position: float
    Value: float
    Error: int


class Intersections(TypedDict):
    TrendLineIntersection: TrendLineIntersection
    HyperbolicMinimum: HyperbolicMinimum


class Fittings(TypedDict):
    Quadratic: str
    Hyperbolic: str
    Gaussian: str
    LeftTrend: str
    RightTrend: str


class RSquares(TypedDict):
    Quadratic: float
    Hyperbolic: float
    LeftTrend: float
    RightTrend: int


class BacklashCompensation(TypedDict):
    BacklashCompensationModel: str
    BacklashIN: int
    BacklashOUT: int


class Response(TypedDict):
    Version: int
    Filter: str
    AutoFocuserName: str
    StarDetectorName: str
    Timestamp: str
    Temperature: float
    Method: str
    Fitting: str
    InitialFocusPoint: InitialFocusPoint
    CalculatedFocusPoint: CalculatedFocusPoint
    PreviousFocusPoint: PreviousFocusPoint
    MeasurePoints: list[MeasurePoint]
    Intersections: Intersections
    Fittings: Fittings
    RSquares: RSquares
    BacklashCompensation: BacklashCompensation
    Duration: str


class FocuserLastAF(TypedDict):
    Response: Response
    Error: str
    StatusCode: int
    Success: bool
    Type: str


class RA(TypedDict):
    Pixel: int
    Arcseconds: int


class Dec(TypedDict):
    Pixel: int
    Arcseconds: int


class Total(TypedDict):
    Pixel: int
    Arcseconds: int


class PeakRA(TypedDict):
    Pixel: int
    Arcseconds: int


class PeakDec(TypedDict):
    Pixel: int
    Arcseconds: int


class RMSError(TypedDict):
    RA: RA
    Dec: Dec
    Total: Total
    PeakRA: PeakRA
    PeakDec: PeakDec


class LastGuideStep(TypedDict):
    RADistanceRaw: float
    DECDistanceRaw: float
    RADuration: float
    DECDuration: float


class GuiderInfo(TypedDict):
    Connected: bool
    Name: NotRequired[str]
    DisplayName: NotRequired[str]
    Description: NotRequired[str]
    DriverInfo: NotRequired[str]
    DriverVersion: NotRequired[str]
    DeviceId: NotRequired[str]
    CanClearCalibration: bool
    CanSetShiftRate: bool
    CanGetLockPosition: bool
    SupportedActions: NotRequired[list[Any]]
    RMSError: NotRequired[RMSError]
    PixelScale: float
    LastGuideStep: NotRequired[LastGuideStep]
    State: NotRequired[
        Literal['Looping', 'LostLock', 'Guiding', 'Stopped', 'Calibrating']
    ]


class DateTime(TypedDict):
    Now: str
    UtcNow: str


class Coordinates(TypedDict):
    RA: float
    RAString: str
    RADegrees: float
    Dec: float
    DecString: str
    Epoch: Literal['JNOW', 'B1950', 'J2000', 'J2050']
    DateTime: DateTime


class MountInfo(TypedDict):
    TrackingMode: NotRequired[
        Literal['Siderial', 'Lunar', 'Solar', 'King', 'Custom', 'Stopped']
    ]
    SiderealTime: NotRequired[float]
    RightAscension: NotRequired[float]
    Declination: NotRequired[float]
    SiteLatitude: NotRequired[float]
    SiteLongitude: NotRequired[float]
    SiteElevation: NotRequired[float]
    RightAscensionString: NotRequired[str]
    DeclinationString: NotRequired[str]
    Coordinates: NotRequired[Coordinates]
    TimeToMeridianFlip: NotRequired[float]
    SideOfPier: NotRequired[Literal['pierEast', 'pierWest', 'pierUnknown']]
    Altitude: NotRequired[float]
    AltitudeString: NotRequired[str]
    Azimuth: NotRequired[float]
    AzimuthString: NotRequired[str]
    SiderealTimeString: NotRequired[str]
    HoursToMeridianString: NotRequired[str]
    AtPark: NotRequired[bool]
    TrackingRate: NotRequired[dict[str, Any]]
    TrackingEnabled: NotRequired[bool]
    TrackingModes: NotRequired[
        list[Literal['Siderial', 'Lunar', 'Solar', 'King', 'Custom', 'Stopped']]
    ]
    AtHome: NotRequired[bool]
    CanFindHome: NotRequired[bool]
    CanPark: NotRequired[bool]
    CanSetPark: NotRequired[bool]
    CanSetTrackingEnabled: NotRequired[bool]
    CanSetDeclinationRate: NotRequired[bool]
    CanSetRightAscensionRate: NotRequired[bool]
    EquatorialSystem: NotRequired[Literal['JNOW', 'B1950', 'J2000', 'J2050']]
    HasUnknownEpoch: NotRequired[bool]
    TimeToMeridianFlipString: NotRequired[str]
    Slewing: NotRequired[bool]
    GuideRateRightAscensionArcsecPerSec: NotRequired[float]
    GuideRateDeclinationArcsecPerSec: NotRequired[float]
    CanMovePrimaryAxis: NotRequired[bool]
    CanMoveSecondaryAxis: NotRequired[bool]
    PrimaryAxisRates: NotRequired[list[dict[str, Any]]]
    SecondaryAxisRates: NotRequired[list[dict[str, Any]]]
    SupportedActions: NotRequired[list[str]]
    AlignmentMode: NotRequired[Literal['AltAz', 'Polar', 'GermanPolar']]
    CanPulseGuide: NotRequired[bool]
    IsPulseGuiding: NotRequired[bool]
    CanSetPierSide: NotRequired[bool]
    CanSlew: NotRequired[bool]
    UTCDate: NotRequired[str]
    Connected: bool
    Name: str
    DisplayName: str
    DeviceId: str


class RotatorInfo(TypedDict):
    CanReverse: bool
    Reverse: bool
    MechanicalPosition: int
    Position: int
    StepSize: float
    IsMoving: bool
    Synced: bool
    SupportedActions: list[Any]
    Connected: bool
    Name: str
    DisplayName: str
    Description: str
    DriverInfo: str
    DriverVersion: str
    DeviceId: str


class SafetyMonitorInfo(TypedDict):
    IsSafe: bool
    SupportedActions: list[Any]
    Connected: bool
    Name: str
    DisplayName: str
    Description: str
    DriverInfo: str
    DriverVersion: str
    DeviceId: str


class WritableSwitch(TypedDict):
    Maximum: int
    Minimum: int
    StepSize: float
    TargetValue: int
    Id: int
    Name: str
    Description: str
    Value: int


class ReadonlySwitch(TypedDict):
    Id: int
    Name: str
    Description: str
    Value: int


class SwitchInfo(TypedDict):
    WritableSwitches: list[WritableSwitch]
    ReadonlySwitches: list[ReadonlySwitch]
    SupportedActions: list[str]
    Connected: bool
    Name: str
    DisplayName: str
    Description: str
    DriverInfo: str
    DriverVersion: str
    DeviceId: str


class WeatherInfo(TypedDict):
    AveragePeriod: int
    CloudCover: int
    DewPoint: float
    Humidity: int
    Pressure: int
    RainRate: str
    SkyBrightness: str
    SkyQuality: str
    SkyTemperature: str
    StarFWHM: str
    Temperature: float
    WindDirection: int
    WindGust: str
    WindSpeed: float
    SupportedActions: list[Any]
    Connected: bool
    Name: str
    DisplayName: str
    Description: str
    DriverInfo: str
    DriverVersion: str
    DeviceId: str


class Rectangle(TypedDict):
    OriginalX: int
    OriginalY: int
    Id: int
    DSOPositionAngle: int
    OriginalOffset: int
    RotationOffset: int
    Rotation: int
    TotalRotation: int
    X: int
    Y: int
    Width: int
    Height: int


class Response1(TypedDict):
    BoundHeight: int
    BoundWidth: int
    CameraHeight: int
    CameraWidth: int
    CameraPixelSize: int
    DecDegrees: int
    DecMinutes: int
    DecSeconds: int
    RAHours: int
    RAMinutes: int
    RASeconds: int
    FieldOfView: int
    FocalLength: int
    HorizontalPanels: int
    VerticalPanels: int
    Rectangle: Rectangle


class FramingAssistantInfo(TypedDict):
    Response: Response1
    Error: str
    StatusCode: int
    Success: bool
    Type: str


class ApplicationSettings(TypedDict):
    Culture: NotRequired[str]
    DevicePollingInterval: NotRequired[int]
    PageSize: NotRequired[int]
    LogLevel: NotRequired[Literal['ERROR', 'WARNING', 'INFO', 'DEBUG', 'TRACE']]


class AstrometrySettings(TypedDict):
    Latitude: NotRequired[float]
    Longitude: NotRequired[float]
    Elevation: NotRequired[int]
    HorizonFilePath: NotRequired[str]


class CameraSettings(TypedDict):
    BitDepth: NotRequired[int]
    BulbMode: NotRequired[
        Literal['NATIVE', 'SERIALPORT', 'SERIALRELAY', 'TELESCOPESNAPPORT']
    ]
    Id: NotRequired[str]
    PixelSize: NotRequired[int]
    RawConverter: NotRequired[Literal['DCRAW', 'FREEIMAGE']]
    SerialPort: NotRequired[str]
    MinFlatExposureTime: NotRequired[float]
    MaxFlatExposureTime: NotRequired[int]
    FileCameraFolder: NotRequired[str]
    FileCameraUseBulbMode: NotRequired[bool]
    FileCameraIsBayered: NotRequired[bool]
    FileCameraExtension: NotRequired[str]
    FileCameraAlwaysListen: NotRequired[bool]
    FileCameraDownloadDelay: NotRequired[int]
    BayerPattern: NotRequired[
        Literal[
            'None',
            'Auto',
            'RGGB',
            'BGGR',
            'GBRG',
            'GRBG',
            'GRGB',
            'GBGR',
            'RGBG',
            'BGRG',
        ]
    ]
    FLIEnableFloodFlush: NotRequired[bool]
    FLIEnableSnapshotFloodFlush: NotRequired[bool]
    FLIFloodDuration: NotRequired[int]
    FLIFlushCount: NotRequired[int]
    BitScaling: NotRequired[bool]
    CoolingDuration: NotRequired[int]
    WarmingDuration: NotRequired[int]
    Temperature: NotRequired[int]
    Gain: NotRequired[int]
    Offset: NotRequired[int]
    QhyIncludeOverscan: NotRequired[bool]
    Timeout: NotRequired[int]
    DewHeaterOn: NotRequired[bool]
    ASCOMAllowUnevenPixelDimension: NotRequired[bool]
    MirrorLockupDelay: NotRequired[int]
    BinAverageEnabled: NotRequired[bool]
    TrackingCameraASCOMServerEnabled: NotRequired[bool]
    TrackingCameraASCOMServerPipeName: NotRequired[str]
    TrackingCameraASCOMServerLoggingEnabled: NotRequired[bool]
    SBIGUseExternalCcdTracker: NotRequired[bool]
    AtikGainPreset: NotRequired[int]
    AtikExposureSpeed: NotRequired[int]
    AtikWindowHeaterPowerLevel: NotRequired[int]
    TouptekAlikeUltraMode: NotRequired[bool]
    TouptekAlikeHighFullwell: NotRequired[bool]
    TouptekAlikeLEDLights: NotRequired[bool]
    TouptekAlikeDewHeaterStrength: NotRequired[int]
    GenericCameraDewHeaterStrength: NotRequired[int]
    GenericCameraFanSpeed: NotRequired[int]
    ZwoAsiMonoBinMode: NotRequired[bool]
    ASCOMCreate32BitData: NotRequired[bool]
    BadPixelCorrection: NotRequired[bool]
    BadPixelCorrectionThreshold: NotRequired[int]


class ColorSchemaSettings(TypedDict):
    AltColorSchema: NotRequired[str]
    ColorSchema: NotRequired[str]


class DomeSettings(TypedDict):
    Id: NotRequired[str]
    ScopePositionEastWest_mm: NotRequired[int]
    ScopePositionNorthSouth_mm: NotRequired[int]
    ScopePositionUpDown_mm: NotRequired[int]
    DomeRadius_mm: NotRequired[int]
    GemAxis_mm: NotRequired[int]
    LateralAxis_mm: NotRequired[int]
    AzimuthTolerance_degrees: NotRequired[int]
    FindHomeBeforePark: NotRequired[bool]
    DomeSyncTimeoutSeconds: NotRequired[int]
    SynchronizeDuringMountSlew: NotRequired[bool]
    SyncSlewDomeWhenMountSlews: NotRequired[bool]
    RotateDegrees: NotRequired[int]
    CloseOnUnsafe: NotRequired[bool]
    ParkMountBeforeShutterMove: NotRequired[bool]
    RefuseUnsafeShutterMove: NotRequired[bool]
    RefuseUnsafeShutterOpenSansSafetyDevice: NotRequired[bool]
    ParkDomeBeforeShutterMove: NotRequired[bool]
    MountType: NotRequired[Literal['EQUATORIAL', 'FORK_ON_WEDGE']]
    DecOffsetHorizontal_mm: NotRequired[int]
    SettleTimeSeconds: NotRequired[int]


class Binning1(TypedDict):
    Name: NotRequired[str]
    X: NotRequired[int]
    Y: NotRequired[int]


class FlatWizardFilterSettings1(TypedDict):
    FlatWizardMode: NotRequired[
        Literal['DYNAMICEXPOSURE', 'DYNAMICBRIGHTNESS', 'SKYFLAT']
    ]
    HistogramMeanTarget: NotRequired[float]
    HistogramTolerance: NotRequired[float]
    MaxFlatExposureTime: NotRequired[int]
    MinFlatExposureTime: NotRequired[float]
    MaxAbsoluteFlatDeviceBrightness: NotRequired[int]
    MinAbsoluteFlatDeviceBrightness: NotRequired[int]
    Gain: NotRequired[int]
    Offset: NotRequired[int]
    Binning: NotRequired[Binning1]


class AutoFocusBinning1(TypedDict):
    Name: NotRequired[str]
    X: NotRequired[int]
    Y: NotRequired[int]


class FilterWheelFilter(TypedDict):
    Name: NotRequired[str]
    FocusOffset: NotRequired[int]
    Position: NotRequired[int]
    AutoFocusExposureTime: NotRequired[int]
    AutoFocusFilter: NotRequired[bool]
    FlatWizardFilterSettings: NotRequired[FlatWizardFilterSettings1]
    AutoFocusBinning: NotRequired[AutoFocusBinning1]
    AutoFocusGain: NotRequired[int]
    AutoFocusOffset: NotRequired[int]


class FilterWheelSettings(TypedDict):
    FilterWheelFilters: NotRequired[list[FilterWheelFilter]]
    Id: NotRequired[str]
    DisableGuidingOnFilterChange: NotRequired[bool]
    Unidirectional: NotRequired[bool]


class FlatWizardSettings(TypedDict):
    FlatCount: NotRequired[int]
    HistogramMeanTarget: NotRequired[float]
    HistogramTolerance: NotRequired[float]
    DarkFlatCount: NotRequired[int]
    OpenForDarkFlats: NotRequired[bool]
    AltitudeSite: NotRequired[int]
    FlatWizardMode: NotRequired[
        Literal['DYNAMICEXPOSURE', 'DYNAMICBRIGHTNESS', 'SKYFLAT']
    ]


class FocuserSettings(TypedDict):
    AutoFocusExposureTime: NotRequired[int]
    AutoFocusInitialOffsetSteps: NotRequired[int]
    AutoFocusStepSize: NotRequired[int]
    Id: NotRequired[str]
    UseFilterWheelOffsets: NotRequired[bool]
    AutoFocusDisableGuiding: NotRequired[bool]
    FocuserSettleTime: NotRequired[int]
    AutoFocusTotalNumberOfAttempts: NotRequired[int]
    AutoFocusNumberOfFramesPerPoint: NotRequired[int]
    AutoFocusInnerCropRatio: NotRequired[int]
    AutoFocusOuterCropRatio: NotRequired[int]
    AutoFocusUseBrightestStars: NotRequired[int]
    BacklashIn: NotRequired[int]
    BacklashOut: NotRequired[int]
    AutoFocusBinning: NotRequired[int]
    AutoFocusCurveFitting: NotRequired[
        Literal[
            'TRENDLINES', 'PARABOLIC', 'TRENDPARABOLIC', 'HYPERBOLIC', 'TRENDHYPERBOLIC'
        ]
    ]
    AutoFocusMethod: NotRequired[Literal['STARHFR', 'CONTRASTDETECTION']]
    ContrastDetectionMethod: NotRequired[Literal['Sobel', 'Laplace', 'Statistics']]
    BacklashCompensationModel: NotRequired[Literal['ABSOLUTE', 'OVERSHOOT']]
    AutoFocusTimeoutSeconds: NotRequired[int]
    RSquaredThreshold: NotRequired[float]


class FramingAssistantSettings(TypedDict):
    CameraHeight: NotRequired[int]
    CameraWidth: NotRequired[int]
    FieldOfView: NotRequired[int]
    Opacity: NotRequired[float]
    LastSelectedImageSource: NotRequired[
        Literal[
            'NASA',
            'SKYSERVER',
            'STSCI',
            'ESO',
            'HIPS2FITS',
            'SKYATLAS',
            'FILE',
            'CACHE',
        ]
    ]
    LastRotationAngle: NotRequired[int]
    SaveImageInOfflineCache: NotRequired[bool]


class GuideChartRightAscensionColor(TypedDict):
    A: NotRequired[int]
    R: NotRequired[int]
    G: NotRequired[int]
    B: NotRequired[int]
    ScA: NotRequired[int]
    ScR: NotRequired[int]
    ScG: NotRequired[int]
    ScB: NotRequired[int]


class GuideChartDeclinationColor(TypedDict):
    A: NotRequired[int]
    R: NotRequired[int]
    G: NotRequired[int]
    B: NotRequired[int]
    ScA: NotRequired[int]
    ScR: NotRequired[int]
    ScG: NotRequired[int]
    ScB: NotRequired[int]


class GuiderSettings(TypedDict):
    GuiderName: NotRequired[str]
    DitherPixels: NotRequired[int]
    DitherRAOnly: NotRequired[bool]
    PHD2GuiderScale: NotRequired[Literal['PIXELS', 'ARCSECONDS']]
    MaxY: NotRequired[int]
    PHD2HistorySize: NotRequired[int]
    PHD2ServerPort: NotRequired[int]
    PHD2ServerUrl: NotRequired[str]
    PHD2InstanceNumber: NotRequired[int]
    SettleTime: NotRequired[int]
    SettlePixels: NotRequired[float]
    SettleTimeout: NotRequired[int]
    PHD2Path: NotRequired[str]
    AutoRetryStartGuiding: NotRequired[bool]
    AutoRetryStartGuidingTimeoutSeconds: NotRequired[int]
    MetaGuideUseIpAddressAny: NotRequired[bool]
    MetaGuidePort: NotRequired[int]
    MGENFocalLength: NotRequired[int]
    MGENPixelMargin: NotRequired[int]
    MetaGuideMinIntensity: NotRequired[int]
    MetaGuideDitherSettleSeconds: NotRequired[int]
    MetaGuideLockWhenGuiding: NotRequired[bool]
    PHD2ROIPct: NotRequired[int]
    SkyGuardServerPort: NotRequired[int]
    SkyGuardServerUrl: NotRequired[str]
    SkyGuardPath: NotRequired[str]
    SkyGuardCallbackPort: NotRequired[int]
    SkyGuardTimeLapsChecked: NotRequired[bool]
    SkyGuardValueMaxGuiding: NotRequired[int]
    SkyGuardTimeLapsGuiding: NotRequired[int]
    SkyGuardTimeLapsDitherChecked: NotRequired[bool]
    SkyGuardValueMaxDithering: NotRequired[int]
    SkyGuardTimeLapsDithering: NotRequired[int]
    SkyGuardTimeOutGuiding: NotRequired[int]
    GuideChartRightAscensionColor: NotRequired[GuideChartRightAscensionColor]
    GuideChartDeclinationColor: NotRequired[GuideChartDeclinationColor]
    GuideChartShowCorrections: NotRequired[bool]


class ImageFileSettings(TypedDict):
    FilePath: NotRequired[str]
    FilePattern: NotRequired[str]
    FilePatternDARK: NotRequired[str]
    FilePatternBIAS: NotRequired[str]
    FilePatternFLAT: NotRequired[str]
    FileType: NotRequired[
        Literal['TIFF', 'FITS', 'XISF', 'TIFF_ZIP', 'TIFF_LZW', 'RAW']
    ]
    TIFFCompressionType: NotRequired[Literal['NONE', 'ZIP', 'LZW']]
    XISFCompressionType: NotRequired[Literal['NONE', 'LZ4', 'LZ4HC', 'ZLIB']]
    XISFChecksumType: NotRequired[
        Literal['NONE', 'SHA1', 'SHA256', 'SHA512', 'SHA3_256', 'SHA3_512']
    ]
    XISFByteShuffling: NotRequired[bool]
    FITSCompressionType: NotRequired[
        Literal['NONE', 'RICE', 'GZIP1', 'GZIP2', 'PLIO', 'HCOMPRESS']
    ]
    FITSAddFzExtension: NotRequired[bool]
    FITSUseLegacyWriter: NotRequired[bool]


class ImageSettings(TypedDict):
    AnnotateImage: NotRequired[bool]
    DebayerImage: NotRequired[bool]
    DebayeredHFR: NotRequired[bool]
    UnlinkedStretch: NotRequired[bool]
    AnnotateUnlimitedStars: NotRequired[bool]
    AutoStretchFactor: NotRequired[float]
    BlackClipping: NotRequired[float]
    StarSensitivity: NotRequired[Literal['Normal', 'High', 'Highest']]
    NoiseReduction: NotRequired[Literal['None', 'Median', 'Normal', 'High', 'Highest']]
    DetectStars: NotRequired[bool]
    AutoStretch: NotRequired[bool]


class MeridianFlipSettings(TypedDict):
    MinutesAfterMeridian: NotRequired[int]
    MaxMinutesAfterMeridian: NotRequired[int]
    PauseTimeBeforeMeridian: NotRequired[int]
    Recenter: NotRequired[bool]
    SettleTime: NotRequired[int]
    UseSideOfPier: NotRequired[bool]
    AutoFocusAfterFlip: NotRequired[bool]
    RotateImageAfterFlip: NotRequired[bool]


class PlanetariumSettings(TypedDict):
    StellariumHost: NotRequired[str]
    StellariumPort: NotRequired[int]
    CdCHost: NotRequired[str]
    CdCPort: NotRequired[int]
    TSXHost: NotRequired[str]
    TSXPort: NotRequired[int]
    TSXUseSelectedObject: NotRequired[bool]
    HNSKYHost: NotRequired[str]
    HNSKYPort: NotRequired[int]
    C2AHost: NotRequired[str]
    C2APort: NotRequired[int]
    SkytechXHost: NotRequired[str]
    SkytechXPort: NotRequired[int]
    PreferredPlanetarium: NotRequired[
        Literal['CDC', 'STELLARIUM', 'THESKYX', 'HNSKY', 'C2A', 'SKYTECHX']
    ]


class PlateSolveSettings(TypedDict):
    AstrometryURL: NotRequired[str]
    AstrometryAPIKey: NotRequired[str]
    BlindSolverType: NotRequired[
        Literal['ASTROMETRY_NET', 'LOCAL', 'ASPS', 'ASTAP', 'PLATESOLVE3', 'PINPOINT']
    ]
    CygwinLocation: NotRequired[str]
    ExposureTime: NotRequired[int]
    Gain: NotRequired[int]
    Binning: NotRequired[int]
    PlateSolverType: NotRequired[
        Literal[
            'ASTROMETRY_NET',
            'LOCAL',
            'PLATESOLVE2',
            'PLATESOLVE3',
            'ASPS',
            'ASTAP',
            'TSX_IMAGELINK',
            'PINPONT',
        ]
    ]
    PS2Location: NotRequired[str]
    PS3Location: NotRequired[str]
    Regions: NotRequired[int]
    SearchRadius: NotRequired[int]
    Threshold: NotRequired[int]
    RotationTolerance: NotRequired[int]
    ReattemptDelay: NotRequired[int]
    NumberOfAttempts: NotRequired[int]
    AspsLocation: NotRequired[str]
    ASTAPLocation: NotRequired[str]
    DownSampleFactor: NotRequired[int]
    MaxObjects: NotRequired[int]
    Sync: NotRequired[bool]
    SlewToTarget: NotRequired[bool]
    BlindFailoverEnabled: NotRequired[bool]
    TheSkyXHost: NotRequired[str]
    TheSkyXPort: NotRequired[int]
    PinPointCatalogType: NotRequired[
        Literal[
            'ppGSCACT',
            'ppTycho2',
            'ppUSNO_A',
            'ppUCAC2',
            'ppUSNO_B',
            'ppUCAC3',
            'ppUCAC4',
            'ppAtlas',
        ]
    ]
    PinPointCatalogRoot: NotRequired[str]
    PinPointMaxMagnitude: NotRequired[int]
    PinPointExpansion: NotRequired[int]
    PinPointAllSkyApiKey: NotRequired[str]
    PinPointAllSkyApiHost: NotRequired[str]


class RotatorSettings(TypedDict):
    Id: NotRequired[str]
    Reverse2: NotRequired[bool]
    RangeType: NotRequired[Literal['FULL', 'HALF', 'QUARTER']]
    RangeStartMechanicalPosition: NotRequired[int]


class FlatDeviceSettings(TypedDict):
    Id: NotRequired[str]
    PortName: NotRequired[str]
    SettleTime: NotRequired[int]
    TrainedFlatExposureSettings: NotRequired[list[Any]]


class SequenceSettings(TypedDict):
    EstimatedDownloadTime: NotRequired[str]
    TemplatePath: NotRequired[str]
    TimeSpanInTicks: NotRequired[int]
    ParkMountAtSequenceEnd: NotRequired[bool]
    CloseDomeShutterAtSequenceEnd: NotRequired[bool]
    ParkDomeAtSequenceEnd: NotRequired[bool]
    WarmCamAtSequenceEnd: NotRequired[bool]
    DefaultSequenceFolder: NotRequired[str]
    StartupSequenceTemplate: NotRequired[str]
    SequencerTemplatesFolder: NotRequired[str]
    SequencerTargetsFolder: NotRequired[str]
    CollapseSequencerTemplatesByDefault: NotRequired[bool]
    CoolCameraAtSequenceStart: NotRequired[bool]
    UnparMountAtSequenceStart: NotRequired[bool]
    OpenDomeShutterAtSequenceStart: NotRequired[bool]
    DoMeridianFlip: NotRequired[bool]
    DisableSimpleSequencer: NotRequired[bool]


class SwitchSettings(TypedDict):
    Id: NotRequired[str]


class TelescopeSettings(TypedDict):
    Name: NotRequired[str]
    MountName: NotRequired[str]
    FocalLength: NotRequired[int]
    FocalRatio: NotRequired[int]
    Id: NotRequired[str]
    SettleTime: NotRequired[int]
    SnapPortStart: NotRequired[str]
    SnapPortStop: NotRequired[str]
    NoSync: NotRequired[bool]
    TimeSync: NotRequired[bool]
    PrimaryReversed: NotRequired[bool]
    SecondaryReversed: NotRequired[bool]
    TelescopeLocationSyncDirection: NotRequired[
        Literal['PROMPT', 'TOAPPLICATION', 'TOTELESCOPE', 'NOSYNC']
    ]


class WeatherDataSettings(TypedDict):
    Id: NotRequired[str]
    OpenWeatherMapAPIKey: NotRequired[str]
    TheWeatherCompanyAPIKey: NotRequired[str]
    WeatherUndergroundAPIKey: NotRequired[str]
    WeatherUndergroundStation: NotRequired[str]


class SnapShotControlSettings(TypedDict):
    ExposureDuration: NotRequired[int]
    Gain: NotRequired[int]
    Save: NotRequired[bool]
    Loop: NotRequired[bool]


class SafetyMonitorSettings(TypedDict):
    Id: NotRequired[str]


class AlpacaSettings(TypedDict):
    NumberOfPolls: NotRequired[int]
    PollInterval: NotRequired[int]
    DiscoveryPort: NotRequired[int]
    DiscoveryDuration: NotRequired[int]
    ResolveDnsName: NotRequired[bool]
    UseIPv4: NotRequired[bool]
    UseIPv6: NotRequired[bool]
    UseHttps: NotRequired[bool]


class ImageHistorySettings(TypedDict):
    ImageHistoryLeftSelected: NotRequired[
        Literal[
            'NONE',
            'HFR',
            'Stars',
            'Median',
            'Mean',
            'StDev',
            'MAD',
            'Temperature',
            'Rms',
        ]
    ]
    ImageHistoryRightSelected: NotRequired[
        Literal[
            'NONE',
            'HFR',
            'Stars',
            'Median',
            'Mean',
            'StDev',
            'MAD',
            'Temperature',
            'Rms',
        ]
    ]


class Response2(TypedDict):
    Name: NotRequired[str]
    Description: NotRequired[str]
    Id: NotRequired[str]
    LastUsed: NotRequired[str]
    ApplicationSettings: NotRequired[ApplicationSettings]
    AstrometrySettings: NotRequired[AstrometrySettings]
    CameraSettings: NotRequired[CameraSettings]
    ColorSchemaSettings: NotRequired[ColorSchemaSettings]
    DomeSettings: NotRequired[DomeSettings]
    FilterWheelSettings: NotRequired[FilterWheelSettings]
    FlatWizardSettings: NotRequired[FlatWizardSettings]
    FocuserSettings: NotRequired[FocuserSettings]
    FramingAssistantSettings: NotRequired[FramingAssistantSettings]
    GuiderSettings: NotRequired[GuiderSettings]
    ImageFileSettings: NotRequired[ImageFileSettings]
    ImageSettings: NotRequired[ImageSettings]
    MeridianFlipSettings: NotRequired[MeridianFlipSettings]
    PlanetariumSettings: NotRequired[PlanetariumSettings]
    PlateSolveSettings: NotRequired[PlateSolveSettings]
    RotatorSettings: NotRequired[RotatorSettings]
    FlatDeviceSettings: NotRequired[FlatDeviceSettings]
    SequenceSettings: NotRequired[SequenceSettings]
    SwitchSettings: NotRequired[SwitchSettings]
    TelescopeSettings: NotRequired[TelescopeSettings]
    WeatherDataSettings: NotRequired[WeatherDataSettings]
    SnapShotControlSettings: NotRequired[SnapShotControlSettings]
    SafetyMonitorSettings: NotRequired[SafetyMonitorSettings]
    AlpacaSettings: NotRequired[AlpacaSettings]
    ImageHistorySettings: NotRequired[ImageHistorySettings]


class ProfileInfo(TypedDict):
    Response: NotRequired[Response2]
    Error: NotRequired[str]
    StatusCode: NotRequired[int]
    Success: NotRequired[bool]
    Type: NotRequired[str]


class Response3(TypedDict):
    Conditions: NotRequired[list[Any]]
    Items: NotRequired[list[Any]]
    Triggers: NotRequired[list[Any]]
    Status: NotRequired[str]
    Name: NotRequired[str]


class Response4(TypedDict):
    GlobalTriggers: NotRequired[list[Any]]


class SequenceBaseJson(TypedDict):
    Response: NotRequired[list[Response3 | Response4]]
    Error: NotRequired[str]
    StatusCode: NotRequired[int]
    Success: NotRequired[bool]
    Type: NotRequired[str]


class ResponseItem(TypedDict):
    HasSetupDialog: NotRequired[bool]
    Id: NotRequired[str]
    Name: NotRequired[str]
    DisplayName: NotRequired[str]
    Category: NotRequired[str]
    Connected: NotRequired[bool]
    Description: NotRequired[str]
    DriverInfo: NotRequired[str]
    DriverVersion: NotRequired[str]
    SupportedActions: NotRequired[list[Any]]


class DeviceList(TypedDict):
    Response: NotRequired[list[ResponseItem]]
    Error: NotRequired[str]
    StatusCode: NotRequired[int]
    Success: NotRequired[bool]
    Type: NotRequired[str]


class RMS(TypedDict):
    RA: NotRequired[float]
    Dec: NotRequired[float]
    Total: NotRequired[float]
    RAText: NotRequired[str]
    DecText: NotRequired[str]
    TotalText: NotRequired[str]
    PeakRAText: NotRequired[str]
    PeakDecText: NotRequired[str]
    Scale: NotRequired[float]
    PeakRA: NotRequired[float]
    PeakDec: NotRequired[float]
    DataPoints: NotRequired[int]


class GuideStep(TypedDict):
    Id: NotRequired[int]
    IdOffsetLeft: NotRequired[float]
    IdOffsetRight: NotRequired[float]
    RADistanceRaw: NotRequired[float]
    RADistanceRawDisplay: NotRequired[float]
    RADuration: NotRequired[int]
    DECDistanceRaw: NotRequired[float]
    DECDistanceRawDisplay: NotRequired[float]
    DECDuration: NotRequired[int]
    Dither: NotRequired[str]


class Response5(TypedDict):
    RMS: NotRequired[RMS]
    Interval: NotRequired[int]
    MaxY: NotRequired[int]
    MinY: NotRequired[int]
    MaxDurationY: NotRequired[int]
    MinDurationY: NotRequired[int]
    GuideSteps: NotRequired[list[GuideStep]]
    HistorySize: NotRequired[int]
    PixelScale: NotRequired[float]
    Scale: NotRequired[int]


class GuideStepsHistory(TypedDict):
    Response: NotRequired[Response5]
    Error: NotRequired[str]
    StatusCode: NotRequired[int]
    Success: NotRequired[bool]
    Type: NotRequired[str]


class UnknownError(TypedDict):
    Response: NotRequired[str]
    Error: NotRequired[str]
    StatusCode: NotRequired[int]
    Success: NotRequired[bool]
    Type: NotRequired[str]
