#!/usr/bin/env bash
# Regenerate custom_components/nina_astrophotography/api/v2/schema.py.
#
# The output is COMMITTED and a test diffs against it, so the generator is
# pinned in pyproject's `dev` group. Never hand-edit schema.py.
#
# Source: ninaAPI 2.2.15.2 OpenAPI document, committed at
# docs/v2.0/ninaapi-v2-openapi.yaml.
#
# Fetched from
# https://raw.githubusercontent.com/christian-photo/ninaAPI/2.2.15.2/ninaAPI/api_spec.yaml
# (tag 2.2.15.2, blob sha 6c877086c42a644dbdb4acfea326ae4b75892267) — the rig is
# unreachable from the machine that generated this, so the spec was taken from
# the release rather than the running plugin.
#
# The spec is reliable about response field NAMES and unreliable about types,
# enum values and request parameter names — see design §3.2. Generated types are
# a drift *detector*, not a source of truth; tests/spec_deviations.json records
# every place the wire disagrees.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/custom_components/nina_astrophotography/api/v2/schema.py"

uv run --group dev datamodel-codegen \
  --input "${ROOT}/docs/v2.0/ninaapi-v2-openapi.yaml" \
  --input-file-type openapi \
  --output "${OUT}" \
  --output-model-type typing.TypedDict \
  --target-python-version 3.13 \
  --use-standard-collections \
  --use-union-operator \
  --disable-timestamp \
  --custom-file-header "# GENERATED by scripts/generate_schema.sh — do not edit."

echo "wrote ${OUT}"
