"""schema.py is exactly what the committed spec generates.

A hand-edit to a generated file is invisible in review and survives forever.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "custom_components" / "nina_astrophotography" / "api" / "v2" / "schema.py"


@pytest.mark.slow
def test_schema_regenerates_byte_identically(tmp_path: Path) -> None:
    before = SCHEMA.read_bytes()
    subprocess.run([str(ROOT / "scripts" / "generate_schema.sh")], check=True, cwd=ROOT)
    after = SCHEMA.read_bytes()
    if before != after:
        SCHEMA.write_bytes(before)
        pytest.fail("schema.py differs from what the committed spec generates")


def test_schema_carries_the_generated_header() -> None:
    assert SCHEMA.read_text(encoding="utf-8").startswith(
        "# GENERATED by scripts/generate_schema.sh"
    )
